---
- hosts: all

  tasks:
  - name: run the new module
    sonar_plugin:
      custom_url: https://binaries.sonarsource.com/Distribution/sonar-shay-plugin
    register: testout

  - name: dump test output
    debug:
      msg: '{{ testout }}'

