---
- hosts: all

  tasks:
  - name: run the new module
    sonar_plugin:
      name: C++ (Community)
      state: removed
    register: testout

  - name: dump test output
    debug:
      msg: '{{ testout }}'

